apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer-ms
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: SPRING_PROFILES_ACTIVE
              name: app-config
        - name: SPRING_DATASOURCE_URL
          value: dbc:postgresql://customer-ms-db-service:5432/postgresdb
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_USERNAME
              name: app-config
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_PASSWORD
              name: app-config
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              name: app-config
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              key: SPRING_CLOUD_CONFIG_URI
              name: app-config
        image: asia.gcr.io/scb-online-banking/customerservice:latest
        imagePullPolicy: Always
        name: customerservice
