apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer-ms-db
  name: customer-ms-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer-ms-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        name: postgres